image: node:11.12.0
cache:
  paths:
    - node_modules/
stages:
  - setup
  - test
  - deploy
setup:
  stage: setup
  script: npm install
test:
  stage: test
  script: npm test

deploy_staging:
  stage: deploy
  script:
    - ./node_modules/.bin/now -e NODE_ENV=staging --token=$NOW_TOKEN
    - ./node_modules/.bin/now alias staging-demo-react-hooks --token=$NOW_TOKEN
  environment:
    name: staging
    url: https://staging-demo-react-hooks.now.sh
  only:
    - master

deploy_prod:
  stage: deploy
  script:
    - npm install
    - ./node_modules/.bin/now -e NODE_ENV=production --token=$NOW_TOKEN
    - ./node_modules/.bin/now alias demo-react-hooks --token=$NOW_TOKEN
  environment:
    name: production
    url: https://demo-react-hooks.now.sh
  when: manual
  only:
    - master